import mongoose from "mongoose";
import dotenv from "dotenv";
import Product from "../models/Product.js";

dotenv.config({ path: new URL("../.env", import.meta.url).pathname });

const products = [
  {
    name: "Áo thun nam basic cotton",
    slug: "ao-thun-nam-basic-cotton",
    description: "Áo thun cotton 100% thoáng mát, thấm hút mồ hôi tốt, phù hợp mặc hàng ngày.",
    price: 199000,
    originalPrice: 299000,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500",
    images: [],
    category: "Thời trang",
    brand: "Local Brand",
    stock: 50,
    sold: 120,
    rating: 4.5,
    isActive: true,
  },
  {
    name: "Áo sơ mi nữ công sở trắng",
    slug: "ao-so-mi-nu-cong-so-trang",
    description: "Áo sơ mi nữ dáng suông, vải kate mềm mại, thích hợp môi trường công sở.",
    price: 259000,
    originalPrice: 359000,
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=500",
    images: [],
    category: "Thời trang",
    brand: "No brand",
    stock: 35,
    sold: 85,
    rating: 4.3,
    isActive: true,
  },
  {
    name: "Quần jean nam ống đứng",
    slug: "quan-jean-nam-ong-dung",
    description: "Quần jean co giãn 4 chiều, form ống đứng tôn dáng, bền màu sau nhiều lần giặt.",
    price: 399000,
    originalPrice: 549000,
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=500",
    images: [],
    category: "Thời trang",
    brand: "Denim Co",
    stock: 42,
    sold: 67,
    rating: 4.6,
    isActive: true,
  },
  {
    name: "Điện thoại thông minh XYZ Pro",
    slug: "dien-thoai-thong-minh-xyz-pro",
    description: "Màn hình AMOLED 6.7 inch, camera 108MP, pin 5000mAh, sạc nhanh 65W.",
    price: 7990000,
    originalPrice: 9990000,
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500",
    images: [],
    category: "Điện tử",
    brand: "XYZ",
    stock: 20,
    sold: 45,
    rating: 4.7,
    isActive: true,
  },
  {
    name: "Tai nghe Bluetooth không dây",
    slug: "tai-nghe-bluetooth-khong-day",
    description: "Tai nghe TWS chống ồn chủ động, thời lượng pin 30 giờ, kháng nước IPX5.",
    price: 890000,
    originalPrice: 1290000,
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500",
    images: [],
    category: "Điện tử",
    brand: "SoundMax",
    stock: 60,
    sold: 210,
    rating: 4.4,
    isActive: true,
  },
  {
    name: "Laptop mỏng nhẹ 14 inch",
    slug: "laptop-mong-nhe-14-inch",
    description: "CPU Intel Core i5, RAM 16GB, SSD 512GB, màn hình IPS 2.5K, trọng lượng 1.3kg.",
    price: 15990000,
    originalPrice: 18990000,
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=500",
    images: [],
    category: "Điện tử",
    brand: "TechBook",
    stock: 10,
    sold: 28,
    rating: 4.8,
    isActive: true,
  },
  {
    name: "Serum Vitamin C dưỡng sáng",
    slug: "serum-vitamin-c-duong-sang",
    description: "Serum vitamin C 20% làm sáng da, mờ thâm, chống oxy hóa, phù hợp mọi loại da.",
    price: 450000,
    originalPrice: 620000,
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500",
    images: [],
    category: "Mỹ phẩm",
    brand: "GlowUp",
    stock: 80,
    sold: 340,
    rating: 4.6,
    isActive: true,
  },
  {
    name: "Kem chống nắng SPF50+",
    slug: "kem-chong-nang-spf50",
    description: "Kem chống nắng phổ rộng SPF50+ PA++++, không bết dính, phù hợp dưới lớp makeup.",
    price: 320000,
    originalPrice: 399000,
    image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500",
    images: [],
    category: "Mỹ phẩm",
    brand: "SunShield",
    stock: 95,
    sold: 420,
    rating: 4.5,
    isActive: true,
  },
  {
    name: "Nồi cơm điện tử 1.8L",
    slug: "noi-com-dien-tu-1-8l",
    description: "Nồi cơm điện công nghệ Fuzzy Logic, lòng chống dính, hầm cháo tự động.",
    price: 750000,
    originalPrice: 950000,
    image: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=500",
    images: [],
    category: "Gia dụng",
    brand: "HomeTech",
    stock: 30,
    sold: 55,
    rating: 4.2,
    isActive: true,
  },
  {
    name: "Máy xay sinh tố mini",
    slug: "may-xay-sinh-to-mini",
    description: "Máy xay cầm tay cá nhân 400ml, pin sạc USB, tiện lợi mang đi làm.",
    price: 420000,
    originalPrice: 550000,
    image: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=500",
    images: [],
    category: "Gia dụng",
    brand: "KitchenPro",
    stock: 45,
    sold: 78,
    rating: 4.1,
    isActive: true,
  },
  {
    name: "Balo laptop chống nước",
    slug: "balo-laptop-chong-nuoc",
    description: "Balo 15.6 inch, chất liệu polyester chống nước, nhiều ngăn phụ kiện.",
    price: 550000,
    originalPrice: 750000,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500",
    images: [],
    category: "Phụ kiện",
    brand: "UrbanBag",
    stock: 55,
    sold: 92,
    rating: 4.4,
    isActive: true,
  },
  {
    name: "Đồng hồ thông minh fitness",
    slug: "dong-ho-thong-minh-fitness",
    description: "Theo dõi nhịp tim, SpO2, 100+ chế độ tập luyện, pin 14 ngày, chống nước 5ATM.",
    price: 1890000,
    originalPrice: 2490000,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500",
    images: [],
    category: "Phụ kiện",
    brand: "FitTrack",
    stock: 38,
    sold: 165,
    rating: 4.7,
    isActive: true,
  },
  {
    name: "Sách Đắc Nhân Tâm",
    slug: "sach-dac-nhan-tam",
    description: "Tác phẩm kinh điển của Dale Carnegie về nghệ thuật giao tiếp và ảnh hưởng.",
    price: 89000,
    originalPrice: 120000,
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500",
    images: [],
    category: "Sách",
    brand: "NXB Tổng Hợp",
    stock: 100,
    sold: 560,
    rating: 4.8,
    isActive: true,
  },
  {
    name: "Sách Nhà Giả Kim",
    slug: "sach-nha-gia-kim",
    description: "Tiểu thuyết của Paulo Coelho về hành trình theo đuổi ước mơ.",
    price: 79000,
    originalPrice: 110000,
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=500",
    images: [],
    category: "Sách",
    brand: "NXB Hội Nhà Văn",
    stock: 85,
    sold: 480,
    rating: 4.9,
    isActive: true,
  },
  {
    name: "Áo khoác gió thể thao",
    slug: "ao-khoac-gio-the-thao",
    description: "Áo khoác gió nam nữ, nhẹ, chống gió, có mũ, phản quang khi chạy bộ ban đêm.",
    price: 480000,
    originalPrice: 650000,
    image: "https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=500",
    images: [],
    category: "Thời trang",
    brand: "SportX",
    stock: 48,
    sold: 73,
    rating: 4.3,
    isActive: true,
  },
  {
    name: "Bàn phím cơ cơ học RGB",
    slug: "ban-phim-co-co-hoc-rgb",
    description: "Bàn phím cơ 87 phím, switch Red êm, keycap PBT, đèn RGB tùy chỉnh.",
    price: 1250000,
    originalPrice: 1650000,
    image: "https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=500",
    images: [],
    category: "Điện tử",
    brand: "KeyMaster",
    stock: 25,
    sold: 58,
    rating: 4.6,
    isActive: true,
  },
];

const seedProducts = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("Connected to MongoDB, seeding...");

    await Product.deleteMany({});
    console.log("Cleared existing products");

    await Product.insertMany(products);
    console.log(`Seeded ${products.length} products`);

    await mongoose.disconnect();
    console.log("Disconnected from MongoDB");
    process.exit(0);
  } catch (error) {
    console.error("Seed error:", error.message);
    process.exit(1);
  }
};

seedProducts();
